// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import dataful "github.com/Amazeful/dataful"
import mock "github.com/stretchr/testify/mock"

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// Disconnect provides a mock function with given fields: ctx
func (_m *Database) Disconnect(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository provides a mock function with given fields: db, col
func (_m *Database) Repository(db dataful.DBName, col dataful.Collection) dataful.Repository {
	ret := _m.Called(db, col)

	var r0 dataful.Repository
	if rf, ok := ret.Get(0).(func(dataful.DBName, dataful.Collection) dataful.Repository); ok {
		r0 = rf(db, col)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dataful.Repository)
		}
	}

	return r0
}
