// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import helix "github.com/Amazeful/helix"
import mock "github.com/stretchr/testify/mock"

// TwitchAPI is an autogenerated mock type for the TwitchAPI type
type TwitchAPI struct {
	mock.Mock
}

// NewAPI provides a mock function with given fields: options
func (_m *TwitchAPI) NewAPI(options *helix.Options) (*helix.Client, error) {
	ret := _m.Called(options)

	var r0 *helix.Client
	if rf, ok := ret.Get(0).(func(*helix.Options) *helix.Client); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helix.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*helix.Options) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
